### PR TITLE
Users can control the max number of HTTP Connections and sizes of bulk downloads

### PR DESCRIPTION
**Pull request by zippo227**
@brettharrison had to take it upon himself to reduce the maximum size that Couchbase Lite tries to download at once. When users are on bad connections, the bulk downloads would fail every time because they were too large. He also noticed several issues with concurrent download threads, so he created a parameter to reduce the number of maximum http connections to allow at once.

I fixed several places where the dll would crash hard because things were not null checked. Other pieces of code that could throw exceptions were for some reason being performed outside of the try catch. We request you pull these changes into the main repository to benefit others and move this dll along.

### CODE REVIEW

**Comment by zgramana** [comment]
Thanks for the pull request! We will review this this week, but before we can accept, we need @brettharrison and Andy Martin to sing the [New Contributor Agreement](http://review.couchbase.org/#/settings/agreements).

**Comment by borrrden** [comment]
This pull request cannot be accepted as it is, since it undoes a lot of .NET 3.5 compatibility stuff.  I'll work on it a bit when I get the chance.

**Comment by zippo227** [comment]
@borrrden the intention was not to break that compatibility. Hopefully those side-affects can be easily remedied. We are targetting .NET 4.5, so I can imagine something haven broken for the earlier .NET versions. @brettharrison and I are in process of getting approval to sign the contribution agreement.

**Comment by borrrden** [comment]
Well, for example there are some places where lines containined #if NET_3_5 have been deleted.  If you could undo that kind of stuff on your end it would help the process move along faster :).  Otherwise I will do it sometime this week.

**Comment by zippo227** [comment]
@borrrden I did a pass through the files and reverted the changes you suggested. I'm sure you will also need to do a pass through, but I took care of the things that stuck out to me as unnecessarily different between origin and our fork. I also fixed a case where your master was not using the StringEx.

**Comment by zippo227** [comment]
@zgramana we've both submitted the Contributor Agreement.

**Comment by borrrden** [comment]
Well I merged things according to the GitHub instructions but I guess because I rebased it didn't detect the change, so I had to manually close the PR.  It is merged though, with some stylistic changes.

**Comment by zippo227** [comment]
@borrrden I'm very glad to have our contributions in the official repository.

**Pull request closed without merging**
