### PR TITLE
Migrate from nuspec to csproj based packaging

### PR DESCRIPTION
**Pull request by borrrden**

### CODE REVIEW

**Comment by borrrden** [comment]
Note, there are no functional changes in this PR.  Everything here is related to how packages are generated.

**Comment by borrrden** [comment]
Validation failure unrelated because no functional change

**Comment by borrrden** [comment]
Companion to https://github.com/couchbaselabs/couchbase-lite-net-ee/pull/148

**Review by bmeike — APPROVED** [review]
I really have no idea what this is about.  If it weren't for the fact that you are gonna be back on the case before the next release, I'd have to insist that you explain it all to me.

Just in case you decide to have another kid, you might want to document this: explain, generally, what is going on.

... which reminds me... I ought to do the same thing.

**Comment by bmeike** [comment]
.... oh... and the "all checks have failed thing....   Sigh.

**Review by pasin — APPROVED** [review]

**Pull request merged**
