### PR TITLE
Fix compilation error for .NET iOS

### PR DESCRIPTION
**Pull request by borrrden**
Add more steps to PR validation to catch this issue

### CODE REVIEW

**Comment by borrrden** [comment]
Note: depends on https://github.com/couchbaselabs/couchbase-lite-net-ee/pull/194

**Review by bmeike — APPROVED** [review]
Don't quite understand this change.  Can't review it carefully.

**Comment by borrrden** [comment]
My bad I forgot to include an explanation.  Essentially every time I make a cherry pick from 3.x these days I have to refactor calls to LiteCore to use the new thread safety layer (NativeSafe).  I forgot to do that in a previous commit and it wasn't caught because the only configuration that gets built is Windows and this was in iOS only code.  Now the PR validation will compile all platforms for both CE and EE.

**Comment by borrrden** [comment]
The "JUST_CSHARP" stuff is so that I can compile all of the C# without needlessly downloading LiteCore.

**Pull request merged**
