### PR TITLE
Url issue

### PR DESCRIPTION
**Pull request by jonlipsky**
Fixed an issue doing reachability test with basic authentication.
Fixed a possible (based on timing) null pointer exception starting the replication process.

### CODE REVIEW

**Comment by borrrden** [comment]
Hey nice to hear from you again!  Would you mind telling me what the issue was with the basic auth?  I ran into this problem before and corrected it by adding lines 72 - 75.  If the authorization is incorrect usually it is returned as a WebException, but I don't really care that it did that because it still means the URL is reachable.  So I checked for a WebException and still return true if it is a protocol error.  Has this stopped working for you?

**Comment by jonlipsky** [comment]
Hi Jim, yes, it stopped working for me with the latest versions of
Xamarin.iOS.  I had to add this code to detect and use basic authentication
to get it to work, otherwise the request would simply timeout.

**Comment by borrrden** [comment]
That's weird, is that normal CouchDB behavior?  The normal behavior for an HTTP server is to return a 401 response.  I'm worried about this code because basic auth is not the only form of authentication that could pass through here (digest auth is on the way as well).

**Comment by jonlipsky** [comment]
CouchDB returns a 401 like you'd expect.  Everything was working fine until
recently, and I think it has to do with Xamarin.  I understand if you don't
want to  accept the pull request, as I'm used to having  to use a slightly
modified version of couchbase lite anyway.  I haven't yet been able to use
a release version in my app without running into some type of issue.

**Comment by borrrden** [comment]
Well, after some research I think that UserInfo only applies to basic auth.  Digest auth doesn't specify the credentials in the URL since it is challenge response so I don't think there is a problem using this as-is.

**Pull request merged**
