### PR TITLE
Issue/506

### PR DESCRIPTION
**Pull request by z000z**
Fixes for Issue 506

### CODE REVIEW

**Comment by borrrden** [comment]
Thanks for submitting this.  I'm going to have to analyze it and apply it to the Unity release branch instead of master (Unity release and master are pretty far apart).  I'll do it sometime next week I think (after I finish up the current ForestDB stuff I am working on).

**Comment by borrrden** [comment]
Also, I may have asked before, but have you signed the (electronic) contributor agreement?

**Comment by z000z** [comment]
Sounds good, yup all signed.

**Comment by borrrden** [comment]
I don't know if you noticed but we finally have a fix for Issue #481 coming.  Once it lands I'll definitely be making a large Unity sprint including this PR, and I might get to it before but I haven't forgotten about it!

**Comment by z000z** [comment]
Ah that's good to hear I've been trying to watch the Unity patches to see if they had addressed that issue yet or not.

**Comment by borrrden** [comment]
I have to merge this into the unity-ga branch instead of master.  Eventually merging into master will be correct but unity-ga has gotten out of sync while waiting on Issue #481.  However most of the PR does not apply to unity-ga, so I simply made a commit with the relevant info from this PR and referenced this page.  The commit is in issue/523 since the two seem to be related (another customer is experiencing the same error message with HTTPS requests).

**Pull request closed without merging**
