### PR TITLE
Added PCL lib

### PR DESCRIPTION
**Pull request by jasells**
I pulled out Interfaces for all public classes in the Shared code to create Couhchbase.Lite.Portable  (PCL). This PCL can be used to create PCL business logic libs, and used with Xamarin Forms.

I haven't created an example using Xamarin Forms yet, but the existing examples could be ported to a forms example.  I have not tested sync with server, but local functionality works in both iOS and android tests, but the only changes are to support use of the portable interface definitions.

I created this to suport a project I am working currently and and I need to support multiple platforms with portable business logic.  I also commented on the couchbase forums. http://forums.couchbase.com/t/trying-to-build-couchbase-lite-ios/2019

---
This change is [Reviewable](https://reviewable.io/reviews/couchbase/couchbase-lite-net/354)

### CODE REVIEW

**Comment by borrrden** [comment]
@jasells The files in question don't appear to exist anywhere.  I cannot get your fork to build.  Could you confirm the status of the three files in question, plus one more?

* Shared/Util/DatabaseHolder.cs
* Shared/Util/IDatabaseHolder.cs
* Shared/ClassDiagram.cd
* iOS/test_cases.cs

**Comment by zgramana** [comment]
@jasells if you can commit the missing files by this coming Friday, we can continue reviewing this PR. Otherwise, we'll close this out and revisit it later in 1.1.

**Comment by jasells** [comment]
Hey, I'll take a look.  I didn't get notifications on this thread, so I just saw your questions.  =( 

This thread was marked as spam... sorry!

**Comment by jasells** [comment]
So, the ClassDiagram.cd is just a diagram, so it shouldn't be required to build.... I don't think i generated it, but maybe I did.  Anyway, should be safe to remove, if it is causing problems.

I did add these in my branch, so they wouldn't be in master.  They just help handle internal database ref/de-ref'ing, reduce casting,and consolidates common impl in  Replication, Query, and Document classes as a base class impl and and Interface contract for a class that "holds" a ref to an IDatabase object.

Shared/Util/DatabaseHolder.cs
Shared/Util/IDatabaseHolder.cs

I think I just added them...  sorry, I'm new to git.  I had some local repo confusion... i think?  Those two files now appear to be in the git cloud. =) 

-iOS/test_cases.cs
I have no idea what this file is.  I can't find it, nor did I work in this code at all, so .... maybe it is artifact of my working branch starting from much older main branch?

**Comment by borrrden** [comment]
@jasells Thanks for your response.  I still can't get it to build because now there seems to be another file missing (IAttachment).  Can you verify that you can clone your repo from github into a new directory and build it?

**Comment by jasells** [comment]
Will try that.  Seems like my first attempt with git is not so stellar.






Sent from Surface





From: Jim Borden
Sent: ‎Thursday‎, ‎January‎ ‎22‎, ‎2015 ‎9‎:‎40‎ ‎PM
To: couchbase/couchbase-lite-net
Cc: Joshua Sells





@jasells Thanks for your response. I still can't get it to build because now there seems to be another file missing (IAttachment). Can you verify that you can clone your repo from github into a new directory and build it?

**Comment by jasells** [comment]
OK, it looks like I created a new solution file named CouchbaseLIte.VS2013.sln.  It contains the Couchbase.Lite.Portable project, which contains the IAttachment definition.  You can either use that sln, or add the portable project to the original sln, or I can add it so the two slns are the same.  I guess I made a different one just in case VS made changes that were not nice to Xamarin IDE before adding the new portable project, but I think that was just paranoia.

**Comment by borrrden** [comment]
@jasells Alright, I got it.  This would require a refactoring of all of our unit tests, so it may be a while before this gets merged but I'll keep it on my plate.

**Comment by jasells** [comment]
Well, the good thing is that it doesn't change existing code written to the current API, so the current unit test will still work.  But, they won't test the interfaces, however, they're only interfaces, so there's not much to test.  But I understand your caution. Let me know if there are any other problems!

=)

**Comment by mahabaleshwarhnr** [comment]
@jasells Can you create one example? It is very helpful to many  who is looking couchbase lite for Xamarin.Forms PCL solution.
Thanks

**Comment by borrrden** [comment]
Just as an update on this, we aren't going to be merging this pull request as we have decided to take a different approach.  It has several names, though the more interesting one is "bait and switch".  You can read more about it [here](http://log.paulbetts.org/the-bait-and-switch-pcl-trick/).  I don't have a timeline to share with you about when this will be started, but it's possible you could try doing it yourself if you are in a hurry :).  I'm going to leave this PR open for the time being so that I don't get new ones about it.

**Comment by jasells** [comment]
Well, if there is an update to the SQLite libs, it may be possible to go
completely PCL on the Couchbase side w/o this "bait and switch" tactic.  I
forget which line it was, but there was seemingly a single line of code
that kept the SQLlite lib from compiling as PCL.

On Sun, Apr 19, 2015 at 11:07 PM, Jim Borden <notifications@github.com>
wrote:

> Just as an update on this, we aren't going to be merging this pull request
> as we have decided to take a different approach. It has several names,
> though the more interesting one is "bait and switch". You can read more
> about it here <http://log.paulbetts.org/the-bait-and-switch-pcl-trick/>.
> I don't have a timeline to share with you about when this will be started,
> but it's possible you could try doing it yourself if you are in a hurry :).
> I'm going to leave this PR open for the time being so that I don't get new
> ones about it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/couchbase/couchbase-lite-net/pull/354#issuecomment-94351135>
> .
>



-- 
Thanks,
Joshua A. Sells

**Comment by jasells** [comment]
Just take any existing couchbase lite example and replace the declaration with the interface instead of the concrete class.
I don't have an example easy to share at the moment. I'll look into it.

Sent from my Verizon Wireless BlackBerry

-----Original Message-----

**Comment by kjeremy** [comment]
:+1: for PCL support.

**Comment by borrrden** [comment]
This is old, but Nuget 3.x has some interesting additions to formally support the bait and switch style of PCL libraries.  Once support for Nuget 3.x reaches Xamarin Studio, I think we can start moving forward with this.

**Comment by borrrden** [comment]
Nuget support has finally been realized, and as part of the spurt to support UWP, I am going to make an effort to move to the .NET standard.  This PR and its contents have served their purpose, and so I will close it.

**Pull request closed without merging**
