### PR TITLE
CBL-6325: Implement MmapEnabled property on DatabaseConfiguration

### PR DESCRIPTION
**Pull request by borrrden**
Also

- Support for tool based test spec verification (ImplementsTestSpecAttribute)

### CODE REVIEW

**Comment by borrrden** [comment]
This cherry pick applied cleanly, it should look virtually identical to the original 3.2 PR

**Comment by borrrden** [comment]
There were a few cleanups needed from the cherry pick:

- Consolidate the definition of FLSliceResult in Fleece.cs (it had two different partial defs, so I made it into just one)
- Fix MmapTest to account for the new thread safety API (need to use RawDatabase)

**Comment by borrrden** [comment]
The same unrelated test is failing.  Something is wrong with the machine I think, making it so slow as to time out on that test.  But I don't think I have an alternative machine to run on.

**Review by pasin — APPROVED** [review]
Noticed that `config.flags |= C4DatabaseFlags.DiskSyncFull;` is commented out.

**Comment by borrrden** [comment]
Good catch.  I have a compiler warning in place to remind myself to fix that later, when I go through the compiler warnings.

**Pull request merged**
