### PR TITLE
Separate storage engine reads and writes

### PR DESCRIPTION
**Pull request by borrrden**
This will increase concurrency throughput.  Readers will have unlimited access to the database, minus any transactions in progress, and writers will be pumped through a single thread producer/consumer model so that no mutexes are needed on the database end. Fixes Issue #348

### CODE REVIEW

**Comment by zgramana** [comment]
@lipsky can you give this one a whirl?

**Comment by jonlipsky** [comment]
@zgramana I'm almost done with the conversion of the app to unified, so I should be able to test this out tomorrow.

**Comment by zgramana** [comment]
Cheers!

**Comment by jonlipsky** [comment]
@zgramana This version still has problems for me. Only a few documents get synced before it starts failing with this exception:

```
[WARNING] [Threadpool worker] [SqlitePCLRawStorageEngine] Error inserting into table docs
2015-02-04 23:50:23.046 WiseSketch[10799:193530] 19: 
SQLitePCL.Ugly.ugly+sqlite3_exception: Exception of type 'SQLitePCL.Ugly.ugly+sqlite3_exception' was thrown.
  at SQLitePCL.Ugly.ugly.step (SQLitePCL.sqlite3_stmt stmt) [0x00000] in <filename unknown>:0 
  at Couchbase.Lite.Shared.SqlitePCLRawStorageEngine+<InsertWithOnConflict>c__AnonStorey3.<>m__0 () [0x00024] in /Development/ew-llc/github/couchbase-lite-net/src/Couchbase.Lite.Shared/Store/SqlitePclRawStorageEngine.cs:416 
19: 
SQLitePCL.Ugly.ugly+sqlite3_exception: Exception of type 'SQLitePCL.Ugly.ugly+sqlite3_exception' was thrown.
  at SQLitePCL.Ugly.ugly.step (SQLitePCL.sqlite3_stmt stmt) [0x00000] in <filename unknown>:0 
  at Couchbase.Lite.Shared.SqlitePCLRawStorageEngine+<InsertWithOnConflict>c__AnonStorey3.<>m__0 () [0x00024] in /Development/ew-llc/github/couchbase-lite-net/src/Couchbase.Lite.Shared/Store/SqlitePclRawStorageEngine.cs:416 
2015-02-04 23:50:23.047 WiseSketch[10799:193530]   at SQLitePCL.Ugly.ugly.step (SQLitePCL.sqlite3_stmt stmt) [0x00000] in <filename unknown>:0 
  at Couchbase.Lite.Shared.SqlitePCLRawStorageEngine+<InsertWithOnConflict>c__AnonStorey3.<>m__0 () [0x00024] in /Development/ew-llc/github/couchbase-lite-net/src/Couchbase.Lite.Shared/Store/SqlitePclRawStorageEngine.cs:416 
  at SQLitePCL.Ugly.ugly.step (SQLitePCL.sqlite3_stmt stmt) [0x00000] in <filename unknown>:0 
  at Couchbase.Lite.Shared.SqlitePCLRawStorageEngine+<InsertWithOnConflict>c__AnonStorey3.<>m__0 () [0x00024] in /Development/ew-llc/github/couchbase-lite-net/src/Couchbase.Lite.Shared/Store/SqlitePclRawStorageEngine.cs:416 
```

In debug mode with full logging on, I get those exceptions on about half the runs; however it always seems to recover and all of the documents eventually get synced.

In release mode (and in debug mode with logging turned off), I get those exceptions; however it never recovers and it only syncs a few documents.

In my app, here's what I do:
1) The user logs in (I need the username so I set a filter to only sync certain documents)
2) The database is created.
3) A puller is started
4) A pusher is started
5) A live query is started to monitor the user's drawings to update a table view (this table view used the "CouchbaseTableSource" bundle with Couchbase lite).
6) A live query is started to monitor the user's templates to update a table view (this table view uses a custom table source because I need the items presented in section 1, as opposed to section 0)

As a test, I disabled 4, 5, and 6; however I still get the exceptions.

If there is any silver lining, unlike before, this is the only exception that occurs.

**Comment by jonlipsky** [comment]
@zgramana Here's an example of one of these exceptions with full logging turned on:

```
2015-02-05 00:21:33.769 WiseSketch[11630:221732] [DEBUG] [Threadpool worker] [Puller] Couchbase.Lite.Replicator.Puller: inserting 634f6889-815e-4512-8b82-a706fb65df61 System.Collections.Generic.List`1[System.String]
[DEBUG] [Threadpool worker] [Puller] Couchbase.Lite.Replicator.Puller: inserting 634f6889-815e-4512-8b82-a706fb65df61 System.Collections.Generic.List`1[System.String]
2015-02-05 00:21:33.771 WiseSketch[11630:221732] [DEBUG] [Threadpool worker] [SingleThreadTaskScheduler]  --> Queued a task: 10/1
[DEBUG] [Threadpool worker] [SingleThreadTaskScheduler]  --> Queued a task: 10/1
2015-02-05 00:21:33.774 WiseSketch[11630:221732] [DEBUG] [Threadpool worker] [SingleThreadTaskScheduler] Executing task inline.
[DEBUG] [Threadpool worker] [SingleThreadTaskScheduler] Executing task inline.
2015-02-05 00:21:33.777 WiseSketch[11630:221732] [DEBUG] [Threadpool worker] [SingleThreadTaskScheduler] Task was previously Queued, so expect it to error out later.
[DEBUG] [Threadpool worker] [SingleThreadTaskScheduler] Task was previously Queued, so expect it to error out later.
2015-02-05 00:21:33.779 WiseSketch[11630:221732] [DEBUG] [Threadpool worker] [Database] Begin transaction (level 2)
[DEBUG] [Threadpool worker] [Database] Begin transaction (level 2)
2015-02-05 00:21:33.781 WiseSketch[11630:221732] [DEBUG] [Threadpool worker] [Database] Tx delegate starting
[DEBUG] [Threadpool worker] [Database] Tx delegate starting
2015-02-05 00:21:33.782 WiseSketch[11630:221732] [DEBUG] [Threadpool worker] [SqlitePCLRawStorageEngine] RawQuery sql: SELECT doc_id FROM docs WHERE docid=? (634f6889-815e-4512-8b82-a706fb65df61)
[DEBUG] [Threadpool worker] [SqlitePCLRawStorageEngine] RawQuery sql: SELECT doc_id FROM docs WHERE docid=? (634f6889-815e-4512-8b82-a706fb65df61)
2015-02-05 00:21:33.787 WiseSketch[11630:221735] [DEBUG] [Threadpool worker] [SqlitePCLRawStorageEngine] Preparing statement: 'INSERT INTO docs (docid) VALUES (?)' with values: 634f6889-815e-4512-8b82-a706fb65df61
[DEBUG] [Threadpool worker] [SqlitePCLRawStorageEngine] Preparing statement: 'INSERT INTO docs (docid) VALUES (?)' with values: 634f6889-815e-4512-8b82-a706fb65df61
2015-02-05 00:21:33.790 WiseSketch[11630:221735] [WARNING] [Threadpool worker] [SqlitePCLRawStorageEngine] Error inserting into table docs
[WARNING] [Threadpool worker] [SqlitePCLRawStorageEngine] Error inserting into table docs
2015-02-05 00:21:33.798 WiseSketch[11630:221735] 19: 
SQLitePCL.Ugly.ugly+sqlite3_exception: Exception of type 'SQLitePCL.Ugly.ugly+sqlite3_exception' was thrown.
  at SQLitePCL.Ugly.ugly.step (SQLitePCL.sqlite3_stmt stmt) [0x00000] in <filename unknown>:0 
  at Couchbase.Lite.Shared.SqlitePCLRawStorageEngine+<InsertWithOnConflict>c__AnonStorey3.<>m__0 () [0x00024] in /Development/ew-llc/github/couchbase-lite-net/src/Couchbase.Lite.Shared/Store/SqlitePclRawStorageEngine.cs:416 
19: 
SQLitePCL.Ugly.ugly+sqlite3_exception: Exception of type 'SQLitePCL.Ugly.ugly+sqlite3_exception' was thrown.
  at SQLitePCL.Ugly.ugly.step (SQLitePCL.sqlite3_stmt stmt) [0x00000] in <filename unknown>:0 
  at Couchbase.Lite.Shared.SqlitePCLRawStorageEngine+<InsertWithOnConflict>c__AnonStorey3.<>m__0 () [0x00024] in /Development/ew-llc/github/couchbase-lite-net/src/Couchbase.Lite.Shared/Store/SqlitePclRawStorageEngine.cs:416 
2015-02-05 00:21:33.801 WiseSketch[11630:221735]   at SQLitePCL.Ugly.ugly.step (SQLitePCL.sqlite3_stmt stmt) [0x00000] in <filename unknown>:0 
  at Couchbase.Lite.Shared.SqlitePCLRawStorageEngine+<InsertWithOnConflict>c__AnonStorey3.<>m__0 () [0x00024] in /Development/ew-llc/github/couchbase-lite-net/src/Couchbase.Lite.Shared/Store/SqlitePclRawStorageEngine.cs:416 
  at SQLitePCL.Ugly.ugly.step (SQLitePCL.sqlite3_stmt stmt) [0x00000] in <filename unknown>:0 
  at Couchbase.Lite.Shared.SqlitePCLRawStorageEngine+<InsertWithOnConflict>c__AnonStorey3.<>m__0 () [0x00024] in /Development/ew-llc/github/couchbase-lite-net/src/Couchbase.Lite.Shared/Store/SqlitePclRawStorageEngine.cs:416 
2015-02-05 00:21:33.804 WiseSketch[11630:221732] [WARNING] [Threadpool worker] [Database] Error inserting document id
```

**Comment by borrrden** [comment]
@jonlipsky That is very strange.  On my side, that log is a piece of unreachable code.  Did you by any chance remove the "return false" at the beginning of TryExecuteInline in the SingleThreadScheduler (not SingleTaskThreadpool)?

**Comment by jonlipsky** [comment]
I didn't make any changes to couchbase-lite-net, and I can confirm that
"return false" is still there in "TryExecuteInline".

I just double checked (being paranoid) and I do have the latest version
from the issue-348 branch.

BTW - If you want to mail me directly, my email is "jon [at] elevenworks.com
"

**Comment by borrrden** [comment]
@jonlipsky Sorry, the log threw me off because the tag name was old (that line of code is coming from another class) so I deleted the post from here out of embarrassment ^^;.  I have a good idea of *what* is happening, now I just need to get a better clue as to *why*  If I get a particular question I'll shoot you an email.

**Comment by zgramana** [comment]
Will also fix #257

**Pull request merged**
