### PR TITLE
Issue/505

### PR DESCRIPTION
**Pull request by z000z**
This is the proposed fix for issue 505.

### CODE REVIEW

**Comment by borrrden** [comment]
@z000z If you haven't already, please sign the [New Contributor Agreement](http://review.couchbase.org/#/settings/agreements)

**Comment by z000z** [comment]
Should be signed, it's under my sidney.isaacs@milsoft or sidney.isaacs@yahoo.com account.

**Comment by borrrden** [comment]
Ok.  It's silly but I don't have access to who has signed and who hasn't at the moment (working on that) so I need to ask unless I specifically remember.  I'm going to go through these changes and apply them but I'm not going to include the first three commits since they alter the sample project in a way that is meant to test issue #481.  I'll also put this into master after that since it applies to other platforms as well.

**Comment by z000z** [comment]
Oh ok no problem, sounds good to me.

**Comment by borrrden** [comment]
Manually merged

**Pull request closed without merging**
