### PR TITLE
Fix null reference exception when setting cookie

### PR DESCRIPTION
**Pull request by elevine**
This fixes a null reference exception I encountered when using CBL from
my own .Net45 unit tests.  I was getting a null reference exception when
setting the replicator cookies.  The CBL unit test for adding/deleting
cookies seems to work fine without this though.

### CODE REVIEW

**Comment by zgramana** [comment]
Thanks, @elevine! Looks great. Just two things:
 * Tabs > Spaces :)
 * Sign the [New Contributor Agreement](http://review.couchbase.org/#/settings/agreements)

**Comment by elevine** [comment]
@zgramana I signed the agreement.  Do you want me to change it to spaces? We use tabs at work, so I've got VS set to that by default.  Tabs vs Spaces is one battle I choose to stay out of :)

**Comment by zgramana** [comment]
@elevine thanks! And yeah, please change them since everything else is spaces, your code is the oddball. ;) We've setup the Xamarin Studio project preferences to use spaces, but we'll try to do the same for VS so people don't need to think about it.

**Comment by elevine** [comment]
@zgramana The spacing should be fixed with the commits I added.  Let me know otherwise.

**Comment by zgramana** [comment]
Spacing looks good.

Your next commit changed the version of NUnit and made some other csproj rewrite changes. Can you please back those out?

**Comment by elevine** [comment]
Sorry about that, it should be all good with commit 50ceb3d.

**Comment by zgramana** [comment]
No problem. I've only done it about a thousand times myself. :)

**Comment by zgramana** [comment]
And thanks again for the PR.

**Pull request merged**
